config/routes.rb
Rails.application.routes.draw do

  root 'stocks#price_history'

  resources :stocks, only: :index do
    resources :prices, only: :index
    collection do
      get :price_history
      get :search_prices
    end
  end

end

app/models/price.rb
class Price < ActiveRecord::Base
  belongs_to :stock

  validates :stock, presence: true
  validates :date, :price, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  has_many :prices

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  def index
    @stock = Stock.find(params[:stock_id])
    @prices = @stock.prices.order(date: :desc)
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def index
    @stocks = Stock.all.order(id: :desc)
  end

  def price_history
  end

  def search_prices
    stock = Stock.find(params[:stock][:id])

    stock_prices = stock.prices.where(date: 30.days.ago.to_date..1.day.from_now.to_date).order(date: :asc)

    dates = stock_prices.pluck(:date).map {|date| date.strftime('%Y-%m-%d')}
    prices = stock_prices.pluck(:price)

    respond_to do |format|
      format.json { render json: { stock_name: stock.name, dates: dates, prices: prices } }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Stocks"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li= link_to "Stock Price History", price_history_stocks_path
            %li= link_to "All Stocks", stocks_path

    .container
      .row
        = bootstrap_flash
        = yield

app/views/prices/_price.html.haml
%tr{ class: 'price', id: "price_#{price.id}" }
  %td.id= price.id
  %td.name= price.date.strftime('%Y-%m-%d')
  %td.created_at= "$#{price.price}"

app/views/prices/index.html.haml
.container
  .row
    .col-md-12
      %h1.title Price History for stock: #{@stock.name}

      %table#prices.table.table-striped
        %thead
          %tr
            %td ID
            %td Date
            %td Price
        %tbody
          = render @prices

app/views/stocks/_stock.html.haml
%tr{ class: 'stock', id: "stock_#{stock.id}" }
  %td.id= stock.id
  %td.name= stock.name
  %td.created_at= stock.created_at.strftime('%Y-%m-%d')
  %td= link_to 'View Price History', stock_prices_path(stock), :class => 'btn btn-default btn-xs'

app/views/stocks/index.html.haml
.container
  .row
    .col-md-12
      %h1.title Welcome to Stocks page

      %table.table.table-striped
        %thead
          %tr
            %th ID
            %th Name
            %th Created At
            %th
        %tbody
          = render @stocks

app/views/stocks/price_history.html.haml
.container
  .row
    .col-md-12
      %h1.title Welcome to Stock Price History page!

      #stock_price_history
        %p Select a stock and view the price history in past 30 days.

        = form_tag search_prices_stocks_path, method: :get, remote: true, id: 'stock_prices' do
          .stocks
            %label Stock Name
            = collection_select(:stock, :id, Stock.all, :id, :name)
        #price_history_chart
          %canvas#chart